homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/',views.ubah, name="ubah"),
    path('konfirmasi/', views.konfirmasi, name='konfirmasi'),
]

javasc/urls.py
from django.urls import path
from . import views

app_name = 'javasc'

urlpatterns = [
    path('', views.accordion, name='accordion'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('aboutme/', include('javasc.urls')),
]

homepage/models.py
from django.db import models

class Messages(models.Model):
    nama = models.CharField(max_length = 100)
    pesan = models.TextField()
    color = models.CharField(max_length=100, default='#000000')

    def __str__(self):
        return self.nama

javasc/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms
from .models import Messages

class Messages_Form(forms.ModelForm):
    class Meta:
        model = Messages
        fields = ["nama","pesan"]
        labels = {
            'nama' : 'Nama',
            'pesan' : 'Pesan/Status',
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        }
        )

homepage/views.py
from django.shortcuts import render, redirect
from .models import Messages
from .forms import Messages_Form
import random

def index(request):
    form = Messages_Form()
    if request.method == 'POST':
        nama = request.POST['nama']
        pesan = request.POST['pesan']
        Messages.objects.create(nama=nama,pesan=pesan)
    objs = Messages.objects.all().order_by('id')
    return render(request,'index.html',{'form': form, 'objs':objs})

def konfirmasi(request):
    if request.method == "POST":
        form = Messages_Form(request.POST or None)
        return render(request, 'konfirmasi.html', {'nama':form.data['nama'], 'pesan':form.data['pesan']})

def ubah(request, id):
    if request.method == "POST":
        form = Messages.objects.get(pk = id)
        a = str(hex(random.randint(0,255)))[2:]
        b = str(hex(random.randint(0,255)))[2:]
        c = str(hex(random.randint(0,255)))[2:]
        color = a+b+c
        new_color = "#" + color
        form.color = new_color
        form.save()
        return redirect('/')

javasc/views.py
from django.shortcuts import render

# Create your views here.
def accordion(request):
    return render(request, 'accordion.html')

homepage/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
    crossorigin="anonymous">
  </head>
  <body>
    {% block content %}
    <!--Isi Page-->
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" 
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
    crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/index.html
{% load static %}
{% include 'base.html' %}
{% include 'navbar.html' %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Story 7</title>
</head>
<body>
    {% block content %}
    <div class="formnya">
        <form action="konfirmasi/" method="POST">
            {% csrf_token %}    
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-success">Submit</button>
        </form>
    </div>
    <h1 class="status">Status:</h1>
    <br>
    <div class="container">
        <div class="row row-cols-2">
            {% for elemen in objs %}
        <div class="col" style="background-color: {{ elemen.color }};">
            <div class="media" style="background-color: {{ elemen.color }};">
                <img src="{% static 'picture.jpg' %}" class="mr-3" alt="unknown">
                <div class="media-body">
                  <h5 class="mt-0">{{ elemen.nama }}</h5>
                  <p>{{ elemen.pesan }}</p>
                </div>
            </div>
            <br>
        </div>
        <form action="{{ elemen.id }}/" method="POST">
            {% csrf_token %}
            <button class="btn btn-info" type="submit" name="submits">Change Color!</button>
        </form>
        {% endfor %}
        </div>
    </div>
    {% endblock%}
</body>
</html>

homepage/templates/konfirmasi.html
{% load static %}
{% include 'base.html' %}
{% include 'navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Konfirmasi</title>
</head>
<body>
    <div class="jumbotron">
        <h1 class="display-6">Konfirmasi Pesan:</h1>
        <p class="lead">{{ pesan }}</p>
        <hr class="my-4">
        <p>{{ nama }}</p>
        <form action="/" method="POST">
            {% csrf_token %}
            <input type="hidden" name="nama" value="{{ nama }}">
            <input type="hidden" name="pesan" value="{{ pesan }}">
            <tr>
                <td><a><input class="btn btn-primary btn-lg" type="submit" id="Ya" value="Ya!"></a></td>
                <td><a class="btn btn-danger btn-lg" href="/" role="button" id="Tidak">Tidak!</a></td>
            </tr>
        </form>
    </div>
</body>
</html>

homepage/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'homepage:index' %}">Send Your Status</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" 
    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link" href="{% url 'homepage:index' %}">Beranda <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{% url 'javasc:accordion' %}">About Me</a>
      </div>
    </div>
</nav>
{% block content %}
<!--Isi Page-->
{% endblock %}
</body>
</html>

javasc/templates/accordion.html
{% load static %}
{% include 'base.html' %}
{% include 'navbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'stylejs.css' %}">
    <script src="{% static 'main.js' %}"></script>
    <title>Story 8</title>
    <!-- link JavaScript dari Bootstrap (base.html) -->
</head>
<body>
    <div class="custom-control custom-switch isi-page">
        <button type="button" class="btn btn-info" id="switch">Change Theme!</button>
        
    </div>
    <h1 class="sapaan">Hello, It's <kbd>Me</kbd> !</h1>
    <div class="isi-page">
    <div class="element">
    <button class="accordion" id="acr1"><span>
        <kbd class="move-up up1">Up</kbd> 
        <kbd class="move-down down1">Down</kbd>
    </span> Biodata Saya</button>
    <div class="panel" id="tab1">
        <dl class="row card-body">
            <dt class="col-sm-3">Nama</dt>
            <dd class="col-sm-9">Muhammad Luthfi Fahlevi</dd>
            <dt class="col-sm-3">NPM</dt>
            <dd class="col-sm-9">1906293215</dd>
            <dt class="col-sm-3">Jurusan</dt>
            <dd class="col-sm-9">Ilmu Komputer</dd>
            <dt class="col-sm-3">Hobi</dt>
            <dd class="col-sm-9">Bulutangkis</dd>
        </dl>
    </div>
    </div>
    
    <div class="element">
    <button class="accordion" id="acr2"><span>
        <kbd class="move-up up2">Up</kbd> 
        <kbd class="move-down down2">Down</kbd>
    </span>Activitas Saya</button>
    <div class="panel" id="tab2">
        <div class="card-body">
            <h5 class="card-title">Kuliah Online</h5>
            <p class="card-text">Belajar dan menempuh perkuliahan semester 2 secara online. 
                Kebijakan ini dibuat agar mencegah penyebaran Covid-19.</p>
            <h5 class="card-title">Ngoding</h5>
            <p class="card-text">Sesuai jurusan bro, hehe.</p>
        </div>
    </div>
    </div>

    <div class="element">
    <button class="accordion" id="acr3"><span>
        <kbd class="move-up up3">Up</kbd> 
        <kbd class="move-down down3">Down</kbd>
    </span> Pengalaman Organisasi/Kepanitiaan</button>
    <div class="panel" id="tab3">
        <div class="card-body">
            <h5 class="card-title">Paguyuban Harati UI KalTeng</h5>
            <p class="card-text"><ul>
                    <li>Kepala Bidang Acara & Sosialisasi</td>
                    <li>Wakil Kepala Bidang Kreasi Mahasiswa</td>
            </ul></p>
            <h5 class="card-title">FUKI</h5>
            <p class="card-text"><ul><li>Staff Departemen Qur'an</li></ul></p>
        </div>
    </div>
    </div>

    <div class="element">
    <button class="accordion" id="acr4"><span>
        <kbd class="move-up up4">Up</kbd> 
        <kbd class="move-down down4">Down</kbd>
    </span> Prestasi</button>
    <div class="panel" id="tab4">
    <div class="card-body">
        <p class="card-text">
            <ul>
                <li>Awardee Beasiswa Unggulan Masyarakat Berprestasi 2020 oleh Kemendikbud</li>
                <li>Juara 1 Cerdas Cermat Statistika BPS se-KalTeng 2018</li>
                <li>Juara 1 Mathematics Olympiad Competition UPR se-KalTeng-Sel 2018</li>
                <li>Juara 1 Olimpiade Fisika UPR se-KalTeng 2018</li>
            </ul>
    </div>
    </div>
    </div>
    </div>
    <p class="card-text"><small class="text-muted">Last updated: 17 April 2020 </small></p>
</body>
</html>